/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urna_eletronica;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Image;
import java.net.URL;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author kbelo
 */
public class Candidato extends javax.swing.JFrame    {

  ImageIcon image;
  boolean foto=true;
     int bozo;
     int Dilma;
     int branco;
     int nulo;
    
          
    /**
     * Creates new form Candidato
     */
    public Candidato() {
    
        initComponents();
         setLocationRelativeTo(null);
         //caixaTexto.requestFocus();
  
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        caixaTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Limage = new javax.swing.JLabel();
        nome_candidato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });

        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });

        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });

        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });

        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });

        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });

        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });

        btn0.setText("0");
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 102, 0));
        jButton11.setText("Corrigir");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 204, 0));
        jButton12.setText("Confirma");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Branco");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        caixaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caixaTextoKeyReleased(evt);
            }
        });

        jLabel1.setText("Foto do Candidato");

        jLabel2.setText("Digite o Numero do Candidato");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn1)
                                    .addComponent(btn4)
                                    .addComponent(btn7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn3))
                                    .addComponent(btn0)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn5)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn8)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn9))))
                            .addComponent(caixaTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Limage, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nome_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(caixaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7)
                            .addComponent(btn8)
                            .addComponent(btn9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn5)
                            .addComponent(btn4)
                            .addComponent(btn6)))
                    .addComponent(Limage, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn3)
                        .addComponent(btn2)
                        .addComponent(btn1))
                    .addComponent(nome_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btn0)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
                      caixaTexto.setText(caixaTexto.getText()+"9");
  
   if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }

 
    }//GEN-LAST:event_btn9MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
                               caixaTexto.setText(caixaTexto.getText()+"8");
  //recebeTexto.setText("7");
                                if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }
 
                 


    }//GEN-LAST:event_btn8MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
                caixaTexto.setText(caixaTexto.getText()+"6");
  //recebeTexto.setText("7");
  if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }

    }//GEN-LAST:event_btn6MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        // TODO add your handling code here:
                caixaTexto.setText(caixaTexto.getText()+"5");
  //recebeTexto.setText("7");
   if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }
 

    }//GEN-LAST:event_btn5MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
                caixaTexto.setText(caixaTexto.getText()+"4");
  //recebeTexto.setText("7");
                
   if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }

    }//GEN-LAST:event_btn4MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
                caixaTexto.setText(caixaTexto.getText()+"3");
  //recebeTexto.setText("7");
                    if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }
      

    }//GEN-LAST:event_btn3MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
                caixaTexto.setText(caixaTexto.getText()+"2");
  //recebeTexto.setText("7");
                    if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }
                
   
 
    

    }//GEN-LAST:event_btn2MouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        
         
               caixaTexto.setText(caixaTexto.getText()+"1");
                
               
                   if (caixaTexto.getText().length()>=3){
                condicao(caixaTexto.getText());
                        }
   
 
 
 
               
  //recebeTexto.setText("7");
  
     

    }//GEN-LAST:event_btn1MouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        // TODO add your handling code here:
                caixaTexto.setText(caixaTexto.getText()+"0");
                 
   if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }

    }//GEN-LAST:event_btn0MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        Tela_bloqueio most = new Tela_bloqueio();
        most.Bozo = bozo;
        most.Dilma=Dilma;
        most.branco=branco;
        most.nulo=nulo;
        if (caixaTexto.getText().equals("12")){
            most.Dilma=Dilma + 1;
         // caixaTexto.setText("");
         // Limage.setIcon(null);
          // nome_candidato.setVisible(false);
           chamaAudio();
         
            JOptionPane.showMessageDialog(null,"Obrigado pelo voto");
            dispose();
           most.setVisible(true);
          
        }else if (caixaTexto.getText().equals("17")){
             most.Bozo=bozo + 1; 
         // caixaTexto.setText("");
         // Limage.setIcon(null);
         //  nome_candidato.setVisible(false);
           chamaAudio();
           JOptionPane.showMessageDialog(null,"Obrigado por jogar seu voto no lixo");
          dispose();
            most.setVisible(true); 
        
        }else if (nome_candidato.getText().equals("VOTO EM BRANCO"))  {
            most.branco=branco + 1;
             //  caixaTexto.setText("");
       //   Limage.setIcon(null);
         //  nome_candidato.setVisible(false);
           chamaAudio();
           JOptionPane.showMessageDialog(null,"Fim");
           dispose();
            most.setVisible(true);
        }else{
            
            most.nulo=nulo+1;
              // caixaTexto.setText("");
        //  Limage.setIcon(null);
         //  nome_candidato.setVisible(false);
           chamaAudio();
           JOptionPane.showMessageDialog(null,"Fim");
            dispose();
            most.setVisible(true);
           
        }      
       
      
    }//GEN-LAST:event_jButton12MouseClicked

    private void caixaTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaTextoKeyReleased
        // TODO add your handling code here:
   
                       
                  if (evt.getSource()==caixaTexto){
                      
                   if ((foto) && (caixaTexto.getText().equals("17"))|(caixaTexto.getText().equals("12"))|(caixaTexto.getText().length()>=3)){  
                   
                   condicao(caixaTexto.getText());
           
                   }
                   }
                  
    }//GEN-LAST:event_caixaTextoKeyReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
      
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
         // TODO add your handling code here:
         
          image = new ImageIcon(this.getClass().getResource("/imgs/branco.jpg"));
        Image img = image.getImage(); 
       Image newimg = img.getScaledInstance(Limage.getWidth(), Limage.getHeight(),  java.awt.Image.SCALE_SMOOTH);
       image = new ImageIcon(newimg);
       Limage.setIcon(image);
       nome_candidato.setText("VOTO EM BRANCO"); 
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
         
             

        
     
          
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
           caixaTexto.setText(null);
           Limage.setIcon(null);
           nome_candidato.setText("");
    }//GEN-LAST:event_jButton11MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
        caixaTexto.setText(caixaTexto.getText()+"7");
         if (caixaTexto.getText().length()>=3){
                        
                           condicao(caixaTexto.getText()); 
                        }
    }//GEN-LAST:event_btn7MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed

        

        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed
    
   
  private void chamaAudio(){
       URL url = getClass().getResource("/Som/().getResourcefim.wav");
       AudioClip audio =   Applet.newAudioClip(url);
       audio.play();
    }
    
    private void condicao(String nome){
       
       try{
       image = new ImageIcon(this.getClass().getResource("/imgs/NULO.jpg"));
    }
catch(Exception e){
    image = new ImageIcon(getClass().getResource("/imgs/NULO.png"));  
}
      
    
        
        Image img = image.getImage(); 
       Image newimg = img.getScaledInstance(Limage.getWidth(), Limage.getHeight(),  java.awt.Image.SCALE_SMOOTH);
       image = new ImageIcon(newimg);
        Limage.setIcon(image);
       
             if (caixaTexto.getText().equals("17")){
              nome_candidato.setVisible(true);
            nome_candidato.setText("Bolsótario"); 
            
         }else if (caixaTexto.getText().equals("12")){
               nome_candidato.setVisible(true);
            nome_candidato.setText("Dilma"); 
          
         }else {
                 nome_candidato.setVisible(true);
            nome_candidato.setText("VOTO NULO"); 
         }
          
            
        
        }
         
            
  
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Candidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Limage;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JTextField caixaTexto;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nome_candidato;
    // End of variables declaration//GEN-END:variables

    /**
     * @param Bozo
*/
    public void setBozo(int Bozo) {
        this.bozo = Bozo;
    }

    /**
     * @return the jim
     */
    public int getDilma() {
        return Dilma;
    }

    /**
     * @param Dilma
     */
    public void setDilma(int Dilma) {
        this.Dilma = Dilma;
    }

    /**
     * @return the branco
     */
    public int getBranco() {
        return branco;
    }

    /**
     * @param branco the branco to set
     */
    public void setBranco(int branco) {
        this.branco = branco;
    }

    /**
     * @return the nulo
     */
    public int getNulo() {
        return nulo;
    }

    /**
     * @param nulo the nulo to set
     */
    public void setNulo(int nulo) {
        this.nulo = nulo;
    }

   



  

    


   


 
}
