/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela_bloqueio.java
 *
 * Created on 27/04/2017, 21:34:28
 */
package urna_eletronica;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


import javax.swing.text.MaskFormatter;

/**
 *
 * @author Lab-14-01
 */
public class Tela_bloqueio extends javax.swing.JFrame {
     ImageIcon imageBrasao;
boolean bloqueado=true;

  int Bozo,Dilma,branco,nulo;
    

int resultado;
    /** Creates new form Tela_bloqueio */
    public Tela_bloqueio() {
        initComponents();
         jTextCodigo_desbloqueio.requestFocus();
        setLocationRelativeTo(null);
       
       
        
 imageBrasao= new ImageIcon(this.getClass().getResource("/imgs/GRET.jpg"));
       Image img = imageBrasao.getImage(); 
       Image newimg = img.getScaledInstance(jLBrasao.getWidth(), jLBrasao.getHeight(),  java.awt.Image.SCALE_SMOOTH);
       imageBrasao = new ImageIcon(newimg);
        jLBrasao.setIcon(imageBrasao);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextCodigo_desbloqueio = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jLBrasao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextCodigo_desbloqueio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigo_desbloqueioActionPerformed(evt);
            }
        });
        jTextCodigo_desbloqueio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCodigo_desbloqueioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextCodigo_desbloqueio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Codigo de desbloqueio da urna=56");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 405, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Codigo para ver o numero de votos=123");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 400, 40));

        btSair.setBackground(new java.awt.Color(255, 0, 0));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLBrasao, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 770, 600));
        jLBrasao.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCodigo_desbloqueioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigo_desbloqueioKeyPressed
        // TODO add your handling code here:
           Candidato  telinha = new  Candidato();
                  telinha.branco= branco;
           telinha.Dilma= Dilma;
          telinha.bozo=Bozo;
           telinha.nulo = nulo;
         
          String senha = new String(jTextCodigo_desbloqueio.getPassword());
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            if ((bloqueado)&&(senha.equals("56"))){
                
                  this.dispose();
                telinha.setVisible(true);
          
              
            }else
            if((bloqueado)&& (senha.equals("123"))){
          

                 JOptionPane.showMessageDialog(null,"Bozótario="+String.valueOf(Bozo)+"\n"+" "+"Dilma="+String.valueOf(Dilma)+"\n"+" "+"BRANCO="+String.valueOf(branco)+"\n"+" "+"NULO="+String.valueOf(nulo),"Resultado",
                        JOptionPane.INFORMATION_MESSAGE);
                   jTextCodigo_desbloqueio.setText("");
                   jTextCodigo_desbloqueio.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null,"Urna Bloqueada","Cuidado",
                    JOptionPane.WARNING_MESSAGE);
                jTextCodigo_desbloqueio.setText(null);
                jTextCodigo_desbloqueio.requestFocus();
            }
        }
        
    }//GEN-LAST:event_jTextCodigo_desbloqueioKeyPressed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        
        resultado = JOptionPane.showConfirmDialog(null,"Deseja sair?","Atenção",
                    JOptionPane.YES_NO_OPTION);
        if (resultado== JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Obrigado por continuar");
             jTextCodigo_desbloqueio.requestFocus();
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void jTextCodigo_desbloqueioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigo_desbloqueioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigo_desbloqueioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_bloqueio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_bloqueio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_bloqueio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_bloqueio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Tela_bloqueio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLBrasao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jTextCodigo_desbloqueio;
    // End of variables declaration//GEN-END:variables
}
